### ISSUE TITLE
Feature request/question

### ISSUE THREAD

**Issue by creeperita09** [mon/bad_apple_virus#1]
Would It be possibile to ~~Copy paste~~ repurpose this code to play never gonna give you up instead?

**Comment by mon** [comment]
Absolutely! The hard part will be making/finding a 1bit version of astley's video that will convert cleanly to windows. From there, just use the python script to regenerate the boxes, replace the .ogg file, and it should Just Work. The python script isn't the best, but I can provide help there :)

**Comment by creeperita09** [comment]
thanks! can you provide a requirements.txt? i can't find the modules to install

**Comment by creeperita09** [comment]
also does the script only support black and white?

**Comment by mon** [comment]
> can you provide a requirements.txt? i can't find the modules to install

should be as simple as `pip install pillow cv2 tqdm numpy` but I can probably add a requirements.txt at some point

> also does the script only support black and white?

Correct, because the windows are binary - they either exist or they don't. Perhaps adding custom background colours could be an extension :)

**Comment by creeperita09** [comment]
got the black and white video of never gonna give you up, i can share it if you need it

**Comment by creeperita09** [comment]
huh it's saying that it needs a boxes.json file

**Comment by mon** [comment]
> The script is jank, don't come complaining

The script is split into 2 parts, one generates boxes.json, one generates boxes.bin. Work out which bits to comment out to generate the json

**Comment by creeperita09** [comment]
ok, thanks, i wasn't complaining

**Comment by creeperita09** [comment]
i got it working but the boxes are scaled down? (maybe bc i inputed a 16:9 video) and it abruptly stops

**Comment by mon** [comment]
Does the `apple_frames` folder look sane? Or is it also messed up?

**Comment by creeperita09** [comment]
No the folder Is fine

**Comment by mon** [comment]
Oh right, depending on what you did, you may need to update: https://github.com/mon/bad_apple_virus/blob/master/src/main.rs#L242-L245

**Comment by creeperita09** [comment]
Oh ok, i'll fix It later and i'll make a git repo

**Comment by luRaichu** [comment]
How do I modify the code to make the video loop indefinitely? I'm not a Rust person

**Comment by mon** [comment]
> How do I modify the code to make the video loop indefinitely? I'm not a Rust person

You could try reloading the iterator when the music stops and restarting the music. I won't tell you how, as I don't need this feature.

**Comment by XUANHLGG** [comment]
> got the black and white video of never gonna give you up, i can share it if you need it

How do you convert color video to black and white 1-bit video?I want to use it to play miku miku oo ee oo but I can't find a black and white 1-bit video, thank you.

**Comment by creeperita09** [comment]
> > got the black and white video of never gonna give you up, i can share it if you need it
> 
> How do you convert color video to black and white 1-bit video?I want to use it to play miku miku oo ee oo but I can't find a black and white 1-bit video, thank you.

I used ffmpeg, i don't Remember the command tho

**Comment by XUANHLGG** [comment]
> > > got the black and white video of never gonna give you up, i can share it if you need it
> > 
> > 
> > How do you convert color video to black and white 1-bit video?I want to use it to play miku miku oo ee oo but I can't find a black and white 1-bit video, thank you.
> 
> I used ffmpeg, i don't Remember the command tho

Thanks, I used this command:`ffmpeg -i input.mp4 -f lavfi -i color=gray:s=1080x1920 -f lavfi -i color=black:s=1080x1920 -f lavfi -i color=white:s=1080x1920 -filter_complex threshold output.mp4`

**Comment by Probobcat861** [comment]
I don't get how to run it.

**Comment by Probobcat861** [comment]
Nvm found it
