### ISSUE TITLE
boxes.json

### ISSUE THREAD

**Issue by BOplaid** [mon/bad_apple_virus#10]
It says it needs a boxes.json file, where can I get that?

**Comment by mon** [comment]
Per README:
> Look at bad apple.py for the pre-processing to take an input video and turn it into boxes.bin, a space-optimized representation of the window bounds for each frame. The script is jank, don't come complaining.

(the script is still jank, I haven't merged the PRs to make it better...)

**Comment by BOplaid** [comment]
Can't you at least give a fix for me?
Or merge the PRs? I've never made a Git repo before, but it shouldn't be that hard, right?

**Comment by mon** [comment]
The PRs are not universally an improvement, and I need to spend some time integrating them in a way that I prefer.

You can just check out the PR's repository, it's not that hard, right?
