### ISSUE TITLE
Windows ARM64 binary

### ISSUE THREAD

**Issue by ThatStella7922** [mon/bad_apple_virus#11]
I was looking around and wanted to test this app on a Windows ARM64 system without the binary having to go through emulation, so I cloned the repo and built from commit [b461333](https://github.com/mon/bad_apple_virus/commit/b4613334ad0fc071be3a09bcefec3c1080cde424).

Here's the file: [mon-bad_apple_virus-WindowsARM64.zip](https://github.com/user-attachments/files/16287110/mon-bad_apple_virus-WindowsARM64.zip). Run it through VirusTotal or whatever before running, if you want to. Tested on a laptop with Snapdragon 8cx Gen 2 5G running Windows 11.

**Comment by mon** [comment]
That's cool as! Glad it built with no issues. Does the rust toolchain support fat binaries that run natively on both archs?

**Comment by ThatStella7922** [comment]
Sadly no, and that's not Rust's fault. Windows' PE binary image format has no support for fat binaries.

In general it means that users need to download the right architecture, unless vendors supply an installer built as x86/x86_64 that detects architecture and installs the correct bits on its own.

Side note, it's remarkable how well the 8cx gen 2 keeps up running this program at 1080p lol. It stays synced with the music for the most part.

**Comment by mon** [comment]
I look forward to our efficient ARM overlords
